name: Security Review
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.py'
      - '**/*.java'
      - '**/*.php'
      - '**/*.go'
      - '**/*.rb'
      - '**/Dockerfile'
      - '**/docker-compose.yml'
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  security-review:
    runs-on: ubuntu-latest
    steps:
      - name: Claude Security Analysis
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            @claude /security
            
            Please perform a focused security analysis of this PR:
            1. Look for hardcoded credentials, API keys, or passwords
            2. Check for SQL injection vulnerabilities
            3. Identify XSS vulnerabilities
            4. Review authentication and authorization
            5. Check for insecure data handling
            6. Verify proper error handling
            7. Look for security misconfigurations
            
            Provide specific findings with file locations and recommendations.
          claude_args: |
            --max-turns 5
            --model claude-3-5-sonnet-20241022
